apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow

on:
  push:
    branches:
      - "**"
  workflow_dispatch:
    inputs:
      key1:
        type: string
        default: does it matter
        description: sample input
      key2:
        type: string
        default: mydefault
        description: "yet another "
jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"
          echo "key1: ${{ inputs.key1 }}"
          echo "key2: ${{ inputs.key2 }}"

